//
// Created by Matthew Korkola on 2022-11-28.
//

#ifndef THEFIGHTINGMAIDEN_BLUEWARPTESTCASE_H
#define THEFIGHTINGMAIDEN_BLUEWARPTESTCASE_H


class BlueWarpTestCase {

};


#endif //THEFIGHTINGMAIDEN_BLUEWARPTESTCASE_H
