//
// Created by Matthew Korkola on 2022-11-28.
//

#ifndef THEFIGHTINGMAIDEN_FIREWALLTESTCASE_H
#define THEFIGHTINGMAIDEN_FIREWALLTESTCASE_H


class FireWallTestCase {

};


#endif //THEFIGHTINGMAIDEN_FIREWALLTESTCASE_H
