//
// Created by Matthew Korkola on 2022-11-28.
//

#ifndef THEFIGHTINGMAIDEN_INTERACTWITHNPCTESTCASE_H
#define THEFIGHTINGMAIDEN_INTERACTWITHNPCTESTCASE_H


class InteractWithNPCTestCase {

};


#endif //THEFIGHTINGMAIDEN_INTERACTWITHNPCTESTCASE_H
