//
// Created by Xavier HIll Roy on 2022-11-08.
//

#ifndef THEFIGHTINGMAIDEN_MOVEMENTTESTCASE_H
#define THEFIGHTINGMAIDEN_MOVEMENTTESTCASE_H


class MovementTestCase {

};


#endif //THEFIGHTINGMAIDEN_MOVEMENTTESTCASE_H
